Keywords_table = ['int', 'void', 'char', 'float']
Delimiter_table = ['=', '>', '<', '+', '-', '*', '/', '{', '}', ',', ';', '(', ')', '[', ']']
spaces = [' ', '\n', '\t', '\r']
legal = ['_', '-']

Name_table = []
Type_table = []
Char_table = []
String_table = []
Constant_table = []